### ISSUE TITLE
Trying to get an item off the floor causes a stacktrace in console

### ISSUE THREAD

**Issue by diamond-deluxe** [TheWelshEngineer/DQ-Redux#44]
When pressing [g] while not standing over an item, the following stacktrace appears in the console. There's no indication to the player that anything's gone wrong, but an unhandled exception is still generally bad news! Ideally, in this case, the game should tell the player something like "There's nothing on the ground here." 

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "RogueLike.Main.Items.Item.setOwner(RogueLike.Main.Creatures.Creature)" because "item" is null
        at RogueLike.Main.Creatures.Creature.pickup(Creature.java:2879)
        at RogueLike.Main.AI.PlayerAI.decodeAction(PlayerAI.java:51)
        at RogueLike.Main.AI.PlayerAI.onUpdate(PlayerAI.java:65)
        at RogueLike.Main.Creatures.Creature.update(Creature.java:3855)
        at RogueLike.Main.World.updateOnCurrentFloor(World.java:424)
        at RogueLike.Main.Screens.GameplayScreen.respondToUserInput(GameplayScreen.java:245)
        at RogueLike.Main.applicationMain.keyPressed(applicationMain.java:74)
        at java.desktop/java.awt.Component.processKeyEvent(Component.java:6579)
        at java.desktop/java.awt.Component.processEvent(Component.java:6398)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Window.processEvent(Window.java:2056)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1146)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4877)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by TheWelshEngineer** [comment]
Item ownership was being applied before nullchecking
